# Generated by Django 4.2.6 on 2023-10-09 13:40

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_img', models.ImageField(blank=True, null=True, upload_to='cl-img/')),
                ('client_name', models.CharField(blank=True, max_length=150, null=True)),
                ('client_job', models.CharField(blank=True, max_length=150, null=True)),
                ('name', models.CharField(blank=True, max_length=120, null=True)),
                ('feedback', ckeditor.fields.RichTextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'review',
                'verbose_name_plural': 'Reviews',
            },
        ),
        migrations.CreateModel(
            name='FullView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=130, null=True)),
                ('img', models.ImageField(blank=True, null=True, upload_to='img/')),
                ('img2', models.ImageField(blank=True, null=True, upload_to='img/')),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('url', models.CharField(blank=True, max_length=350, null=True)),
            ],
            options={
                'verbose_name': 'Full',
                'verbose_name_plural': 'Full View',
            },
        ),
        migrations.CreateModel(
            name='Languages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(blank=True, max_length=150, null=True)),
                ('name', models.CharField(blank=True, max_length=120, null=True)),
                ('ability', models.IntegerField()),
            ],
            options={
                'verbose_name': 'language',
                'verbose_name_plural': 'languages',
            },
        ),
        migrations.CreateModel(
            name='myServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(blank=True, max_length=150, null=True)),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'my service',
                'verbose_name_plural': 'My services',
            },
        ),
        migrations.CreateModel(
            name='ProjectCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, null=True)),
                ('category', models.CharField(help_text='Must to be seperated by a "-"', max_length=150)),
            ],
            options={
                'verbose_name': 'project selector',
                'verbose_name_plural': 'project selectors',
            },
        ),
        migrations.CreateModel(
            name='SiteInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='img/favicon')),
                ('statsBgImg', models.ImageField(blank=True, null=True, upload_to='img')),
                ('siteName', models.CharField(blank=True, max_length=250, null=True)),
                ('pageTitle', models.CharField(blank=True, max_length=250, null=True)),
                ('pageSEO', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('contactUsNote', models.CharField(blank=True, max_length=220, null=True)),
                ('phone', models.IntegerField(blank=True, null=True)),
                ('facebook', models.URLField(blank=True, null=True)),
                ('linkedin', models.URLField(blank=True, null=True)),
                ('twitter', models.URLField(blank=True, null=True)),
                ('github', models.URLField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'site',
                'verbose_name_plural': 'site Info',
            },
        ),
        migrations.CreateModel(
            name='Statistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250, null=True)),
                ('icon', models.CharField(blank=True, max_length=150, null=True)),
                ('stats_numb', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'stat',
                'verbose_name_plural': 'statistics',
            },
        ),
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectTitle', models.CharField(blank=True, max_length=250, null=True)),
                ('projectDescribe', models.CharField(blank=True, max_length=250, null=True)),
                ('serviceTitle', models.CharField(blank=True, max_length=250, null=True)),
                ('contactTitle', models.CharField(blank=True, max_length=250, null=True)),
                ('reviewTitle', models.CharField(blank=True, max_length=250, null=True)),
                ('reviewDescribe', models.CharField(blank=True, max_length=250, null=True)),
                ('aboutTitle', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(blank=True, max_length=150, null=True)),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_services', to='webapp.myservices')),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'services',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, null=True)),
                ('img', models.ImageField(blank=True, null=True, upload_to='img/')),
                ('shortDescribe', models.TextField(blank=True, help_text='Max-letters is 50', max_length=50, null=True)),
                ('category_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.projectcategory')),
                ('view_modal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='webapp.fullview')),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
            },
        ),
        migrations.CreateModel(
            name='Intro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='media/logo')),
                ('bgimg', models.ImageField(blank=True, null=True, upload_to='media/')),
                ('img', models.ImageField(blank=True, null=True, upload_to='media/')),
                ('intro', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=150, null=True)),
                ('about', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('language', models.ManyToManyField(related_name='portfolioLanguage', to='webapp.languages')),
            ],
            options={
                'verbose_name': 'Intro',
                'verbose_name_plural': 'Introduction',
            },
        ),
    ]
